services:
  code-server:
    image: lscr.io/linuxserver/code-server:latest
    container_name: code-server
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Bucharest
      - PROXY_DOMAIN=code-server.techcats.org
      - DEFAULT_WORKSPACE=/config/workspace

    env_file:
      - .env

    volumes:
      - /home/daniel/docker/code-server/config:/config
    networks:
      proxy:
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.code-server.entrypoints=http"
      - "traefik.http.routers.code-server.rule=Host(`code-server.techcats.org`)"
      - "traefik.http.middlewares.code-server-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.code-server.middlewares=code-server-https-redirect"
      - "traefik.http.routers.code-server-secure.entrypoints=https"
      - "traefik.http.routers.code-server-secure.rule=Host(`code-server.techcats.org`)"
      - "traefik.http.routers.code-server-secure.tls=true"
      - "traefik.http.routers.code-server-secure.service=code-server"
      - "traefik.http.services.code-server.loadbalancer.server.port=8443"
      - "traefik.docker.network=proxy"
    restart: unless-stopped

networks:
  proxy:
    external: true