services:
  homarr:
    container_name: homarr
    image: ghcr.io/homarr-labs/homarr:latest
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /home/daniel/docker/homarr:/appdata
    env_file:
      - .env
    ports:
      - '7575:7575'
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.homarr.entrypoints=http"
      - "traefik.http.routers.homarr.rule=Host(`homarr.techcats.org`)"
      - "traefik.http.middlewares.homarr-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.homarr.middlewares=homarr-https-redirect"
      - "traefik.http.routers.homarr-secure.entrypoints=https"
      - "traefik.http.routers.homarr-secure.rule=Host(`homarr.techcats.org`)"
      - "traefik.http.routers.homarr-secure.tls=true"
      - "traefik.http.routers.homarr-secure.service=homarr"
      - "traefik.http.services.homarr.loadbalancer.server.port=7575"
      - "traefik.docker.network=proxy"

    networks:
      - proxy

networks:
  proxy:
    external: true

