services:
  minio:
    image: quay.io/minio/minio:latest
    container_name: minio
    restart: unless-stopped
    command: server /data --console-address ":9001"

    env_file:
      - .env

    volumes:
      - /home/daniel/share/minio-data:/data
      - /home/daniel/docker/minio/config:/root/.minio

    networks:
      - proxy

    labels:
      - "traefik.enable=true"

      - "traefik.http.routers.minio-api.rule=Host(`minio-api.techcats.org`)"
      - "traefik.http.routers.minio-api.entrypoints=https"
      - "traefik.http.routers.minio-api.tls.certresolver=cloudflare"
      - "traefik.http.services.minio-api.loadbalancer.server.port=9000"
      - "traefik.http.routers.minio-api.service=minio-api" 

      - "traefik.http.routers.minio-console.rule=Host(`minio.techcats.org`)"
      - "traefik.http.routers.minio-console.entrypoints=https"
      - "traefik.http.routers.minio-console.tls.certresolver=cloudflare"
      - "traefik.http.services.minio-console.loadbalancer.server.port=9001"
      - "traefik.http.routers.minio-console.service=minio-console" 

networks:
  proxy:
    external: true
