services:
  wg-easy:
    environment:
      - WG_HOST=${WG_HOST}
      - PASSWORD=${PASSWORD}
      - WG_DEFAULT_DNS=192.168.10.200
      - WG_MTU=1420
    env_file:
      - .env
      
    image: weejewel/wg-easy
    container_name: wg-easy
    volumes:
      - /home/daniel/docker/wireguard:/etc/wireguard
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      - "traefik.http.routers.wg-easy.entrypoints=http"
      - "traefik.http.routers.wg-easy.rule=Host(`wg-easy.techcats.org`)"
      - "traefik.http.middlewares.wg-easy-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.wg-easy.middlewares=wg-easy-https-redirect"
      - "traefik.http.routers.wg-easy-secure.entrypoints=https"
      - "traefik.http.routers.wg-easy-secure.rule=Host(`wg-easy.techcats.org`)"
      - "traefik.http.routers.wg-easy-secure.tls=true"
      - "traefik.http.routers.wg-easy-secure.tls.certresolver=cloudflare"
      - "traefik.http.routers.wg-easy-secure.service=wg-easy"
      - "traefik.http.services.wg-easy.loadbalancer.server.port=51821"

    networks:
      - proxy

    ports:
      - "51820:51820/udp"
      - "51821:51821/tcp"
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1

networks:
  proxy:
    external: true  